std_msgs/Header header

yhs_can_interfaces/CtrlFb     ctrl_fb
yhs_can_interfaces/IoFb       io_fb

yhs_can_interfaces/LfWheelFb   lf_wheel_fb
yhs_can_interfaces/LrWheelFb   lr_wheel_fb

yhs_can_interfaces/RfWheelFb   rf_wheel_fb
yhs_can_interfaces/RrWheelFb   rr_wheel_fb

yhs_can_interfaces/BmsFlagInfoFb  bms_flag_info_fb 
yhs_can_interfaces/BmsInfoFb      bms_info_fb

yhs_can_interfaces/VehDiagFb      veh_diag_fb
